metadata:
  labels:
    app.openshift.io/runtime: spring-boot
    app.kubernetes.io/part-of: poc
spec:
  template:
    spec:
      containers:
        - env:
            - name: JAVA_DEBUG
              value: "true"
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: '2'
              memory: 2Gi
