kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: view
  namespace: refresh-poc
subjects:
  - kind: ServiceAccount
    name: default
    namespace: refresh-poc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
